export const GET_QUERY_RESULT = 'GET_QUERY_RESULT';
export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL';
export const GET_QUERY_RESULT_SUCCESS = 'GET_QUERY_RESULT_SUCCESS';
export const GET_PRODUCT_DETAIL_SUCCESS = 'GET_PRODUCT_DETAIL_SUCCESS';
export const GET_QUERY_RESULT_FAIL = 'GET_QUERY_RESULT_FAIL';